ALTER TABLE users
  ADD COLUMN username VARCHAR(64) NULL,
  ADD COLUMN password VARCHAR(100) NULL,
  ADD COLUMN role VARCHAR(32) NULL,
  ADD COLUMN org_tags VARCHAR(255) NULL,
  ADD COLUMN created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_time TIMESTAMP NULL;

CREATE UNIQUE INDEX uk_users_username ON users (username);
